// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"github.com/liquidmetal-dev/controller-pkg/types/microvm"
)

type FakeScope struct {
	name   string
	ns     string
	labels map[string]string
	spec   microvm.VMSpec
}

func (s *FakeScope) NameReturns(name string) string {
	s.name = name
	return s.Name()
}

func (s *FakeScope) Name() string {
	return s.name
}

func (s *FakeScope) NamespaceReturns(ns string) string {
	s.ns = ns
	return s.Namespace()
}

func (s *FakeScope) Namespace() string {
	return s.ns
}

func (s *FakeScope) GetLabelsReturns(labels map[string]string) map[string]string {
	s.labels = labels
	return s.GetLabels()
}

func (s *FakeScope) GetLabels() map[string]string {
	return s.labels
}

func (s *FakeScope) GetMicrovmSpecReturns(spec microvm.VMSpec) microvm.VMSpec {
	s.spec = spec
	return s.GetMicrovmSpec()
}

func (s *FakeScope) GetMicrovmSpec() microvm.VMSpec {
	return s.spec
}

func (s *FakeScope) GetInstanceID() string {
	return ""
}

func (s *FakeScope) GetRawBootstrapData() (string, error) {
	return "", nil
}

func (s *FakeScope) GetSSHPublicKeys() []microvm.SSHPublicKey {
	return nil
}
